export const profileItems = [
  {
    id: 1,
    title: "ویرایش پروفایل",
    icon: "info",
    screenName: "AboutMe",
    color: "#8b5cf6",
    permission: "allowAboutMeText",
  },
  {
    id: 2,
    title: " فایل ها و مدارک من",
    icon: "my-library-books",
    screenName: "MyResume",
    color: "#10b981",
    permission: "allowAddDocument",
  },
  {
    id: 3,
    title: "گالری من",
    icon: "image",
    screenName: "MyGallery",
    color: "#f59e0b",
    permission: "allowAddImageGallery",
  },
  {
    id: 4,
    title: "وبلاگ من",
    icon: "article",
    screenName: "MyPosts",
    color: "#06b6d4",
    permission: "allowAddBlogPost",
  },
  {
    id: 5,
    title: "دوره های ثبت نام شده",
    icon: "fact-check",
    screenName: "MyRegistrations",
    color: "#ef4444",
    permission: null, // همیشه در دسترس
  },
  {
    id: 9,
    title: "محصولات من",
    icon: "sell",
    screenName: "MyProduct",
    color: "#81cd4e",
    permission: "allowAddProduct",
  },
  {
    id: 6,
    title: "برگزاری دوره",
    icon: "laptop-chromebook",
    screenName: "MyTeachingCourses",
    color: "#e067c2",
    permission: "allowAddCourse",
  },
  {
    id: 8,
    title: "نمونه کار های من",
    icon: "collections-bookmark",
    screenName: "PortfolioList",
    color: "#6596ff",
    permission: "allowAddPortfolio",
  },
  {
    id: 7,
    title: "اشتراک ها",
    icon: "star",
    screenName: "Subscription",
    color: "#ffd700",
    permission: null, // همیشه در دسترس
  },
];