import { NativeStackNavigationProp } from "@react-navigation/native-stack";

export type RootStackParamList = {
  IntroFlow: undefined;
  App: { screen?: string; params?: any } | undefined;
  Auth: undefined;
  WelcomeIntro: undefined;
  WhyFrimod: undefined;
  EventsScreen: undefined;
  CareerScreen: undefined;
  MainTabs: { screen?: string; params?: any } | undefined;
  Login: undefined;
  OTP: { mobileNumber: string };
  Signup: undefined;
  EditProfile: undefined;
  AboutMe: undefined;
  EditContactInfo: undefined;
  MyResume: undefined;
  MyGallery: undefined;
  AddGallery: undefined;
  MyPosts: undefined;
  MyCourses: undefined;
  ManageGalleryItems: undefined;
  AddNewCourse: undefined;
  MagDetailes: { title?: string; blogId?: number };
  MyTeachingCourses: undefined;
  CourseStudents: undefined;
  MyRegistrations: undefined;
  CourseRegistration: undefined;
  SubscriptionPurchase: undefined;
  AllMemberGroups: undefined;
  AllCourses: { filteredMemberId?: number; filteredMemberName?: string; filterType?: string };
  AllProducts: { filteredMemberId?: number; filteredMemberName?: string; filterType?: string };
  AllMembers: undefined;
  ProductDetails: undefined;
  AddNewPost: undefined;
  PortfolioDetail: { title?: string; portfolioId?: number };
  PortfolioList: undefined;
  AllGalleries: { filteredMemberId?: number; filteredMemberName?: string; filterType?: string };
  AddPortfolio: undefined;
  MyProduct: undefined;
  AddProductScreen: undefined;
  AllPortfolio: { filteredMemberId?: number; filteredMemberName?: string; filterType?: string };
  MagScreen: { filteredMemberId?: number; filteredMemberName?: string; filterType?: string };
  GalleryItem: { title?: string; galleryId?: number };
  Subscription: undefined;
  CourseDetails: { courseData?: any; courseId?: number };
  UserProfile: { userData?: any };
};

export type AppNavigationProp = NativeStackNavigationProp<RootStackParamList>;