

import {
  StyleSheet,
  Dimensions,
  StatusBar,
  Platform
} from "react-native";
import colors from "../../../config/colors";

const { width } = Dimensions.get('window');

export const PROFILE_CONSTANTS = {
  CIRCLE_WIDTH: 1800,
  CIRCLE_HEIGHT: 1800,
  AVATAR_SIZE: 120,
  AVATAR_OUTER_RING: 130,
  AVATAR_MIDDLE_RING: 125,
  BACK_BUTTON_TOP: 90,
  PROFILE_SECTION_TOP: 840,
  CIRCLE_MARGIN_TOP: -1600,
};

export const modernColors = {
  ...colors,
  primary: "#667eea",
  primaryDark: "#764ba2",
  primaryLight: "#f0f4ff",
  secondary: "#ff6b6b",
  tertiary: "#4ecdc4",
  accent: "#45b7d1",
  surface: "#ffffff",
  dark: "#2c3e50",
  medium: "#34495e",
  light: "#ecf0f1",
  success: "#2ecc71",
  warning: "#f39c12",
  error: "#e74c3c",
  info: "#3498db",
  gradientStart: "#667eea",
  gradientEnd: "#764ba2",
};


export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8fafc',
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 40,
  },
  errorText: {
    fontSize: 16,
    fontFamily: "Yekan_Bakh_Bold",
    color: modernColors.error,
    textAlign: 'center',
    marginVertical: 20,
    lineHeight: 24,
  },
  retryButton: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    backgroundColor: modernColors.primary,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 25,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  retryButtonText: {
    fontSize: 14,
    fontFamily: "Yekan_Bakh_Bold",
    color: modernColors.surface,
    marginRight: 8,
  },
  scrollContainer: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingTop: 0,
  },
  topHalfCircle: {
    width: PROFILE_CONSTANTS.CIRCLE_WIDTH,
    height: PROFILE_CONSTANTS.CIRCLE_HEIGHT,
    alignSelf: 'center',
    marginTop: PROFILE_CONSTANTS.CIRCLE_MARGIN_TOP,
    marginBottom: -(PROFILE_CONSTANTS.CIRCLE_HEIGHT * 0.6),
    overflow: 'hidden',
    zIndex: 1,
    borderRadius: PROFILE_CONSTANTS.CIRCLE_WIDTH / 2,
  },
  halfCircleGradient: {
    width: '100%',
    height: '100%',
    borderRadius: PROFILE_CONSTANTS.CIRCLE_WIDTH / 2,
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingTop: 60,
  },
  backButtonContainer: {
    alignSelf: 'flex-end',
    marginTop: PROFILE_CONSTANTS.PROFILE_SECTION_TOP + 100,
    marginBottom: PROFILE_CONSTANTS.PROFILE_SECTION_TOP - 1670,
    zIndex: 4,
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255, 255, 255,0.51)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  profileSection: {
    alignItems: "center",
    padding: 25,
    marginBottom: 40,
    marginTop: PROFILE_CONSTANTS.PROFILE_SECTION_TOP,
    zIndex: 2,
    position: 'relative',
    minHeight: 300,
  },
  avatarContainer: {
    marginBottom: 25,
    position: 'relative',
    zIndex: 3,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarGlowContainer: {
    position: 'relative',
    shadowColor: modernColors.primary,
  },
  avatarOuterRing: {
    width: PROFILE_CONSTANTS.AVATAR_OUTER_RING,
    height: PROFILE_CONSTANTS.AVATAR_OUTER_RING,
    borderRadius: PROFILE_CONSTANTS.AVATAR_OUTER_RING / 2,
    padding: 4,
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarMiddleRing: {
    width: PROFILE_CONSTANTS.AVATAR_MIDDLE_RING,
    height: PROFILE_CONSTANTS.AVATAR_MIDDLE_RING,
    borderRadius: PROFILE_CONSTANTS.AVATAR_MIDDLE_RING / 2,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarInnerContainer: {
    width: PROFILE_CONSTANTS.AVATAR_SIZE,
    height: PROFILE_CONSTANTS.AVATAR_SIZE,
    borderRadius: PROFILE_CONSTANTS.AVATAR_SIZE / 2,
    overflow: 'hidden',
    position: 'relative',
  },
  avatarImage: {
    width: PROFILE_CONSTANTS.AVATAR_SIZE,
    height: PROFILE_CONSTANTS.AVATAR_SIZE,
    borderRadius: PROFILE_CONSTANTS.AVATAR_SIZE / 2,
  },
  defaultAvatar: {
    width: PROFILE_CONSTANTS.AVATAR_SIZE,
    height: PROFILE_CONSTANTS.AVATAR_SIZE,
    borderRadius: PROFILE_CONSTANTS.AVATAR_SIZE / 2,
    justifyContent: "center",
    alignItems: "center",
    position: 'relative',
  },
  blueTickContainer: {
    position: 'absolute',
    bottom: 4,
    right: 4,
    backgroundColor: '#ffffff',
    borderRadius: 15,
    width: 30,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 5,
  },
  avatarDecorations: {
    position: 'absolute',
    width: '100%',
    height: '100%',
  },
  avatarStar1: {
    position: 'absolute',
    top: 12,
    right: 15,
  },
  avatarStar2: {
    position: 'absolute',
    bottom: 15,
    left: 12,
  },
  floatingParticle1: {
    position: 'absolute',
    top: -8,
    right: 15,
  },
  floatingParticle2: {
    position: 'absolute',
    bottom: 8,
    left: -4,
  },
  floatingParticle3: {
    position: 'absolute',
    top: 25,
    left: -12,
  },
  userName: {
    fontSize: 24,
    fontFamily: "Yekan_Bakh_Bold",
    color: modernColors.dark,
    marginBottom: 8,
    textAlign: 'center',
    zIndex: 10,
    position: 'relative',
  },
  userProfession: {
    fontSize: 14,
    fontFamily: "Yekan_Bakh_Regular",
    color: modernColors.medium,
    marginBottom: 20,
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: "rgba(255, 255, 255, 0.8)",
    borderRadius: 50,
    textAlign: 'center',
    zIndex: 9,
    position: 'relative',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  likeSection: {
    position: 'relative',
    alignItems: 'center',
    marginTop: 15,
    zIndex: 8,
    paddingVertical: 10,
  },
  likeButton: {
    borderRadius: 25,
    overflow: 'hidden',
  },
  likeButtonInner: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    paddingHorizontal: 18,
    paddingVertical: 12,
    backgroundColor: "rgba(255, 255, 255, 0.25)",
    backdropFilter: "blur(20px)",
    WebkitBackdropFilter: "blur(20px)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.3)",
  },
  likeText: {
    fontSize: 14,
    fontFamily: "Yekan_Bakh_Bold",
    marginRight: 8,
  },
  floatingHeart: {
    position: 'absolute',
    top: -10,
    alignSelf: 'center',
    pointerEvents: 'none',
  },
  videoSection: {
    marginHorizontal: 0,
    marginBottom: 60,
    marginTop: 20,
    zIndex: 1,
    position: 'relative',
  },
  videoWrapper: {
    borderRadius: 20,
    overflow: 'hidden',
    padding: 4,
  },
  videoShadow: {
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: '#000',
    position: 'relative',
  },
  videoPlayer: {
    width: '100%',
    height: 220,
  },
  videoLoadingContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
    borderRadius: 16,
  },
  videoLoadingIndicator: {
    marginBottom: 15,
  },
  videoLoadingText: {
    fontSize: 14,
    fontFamily: "Yekan_Bakh_Regular",
    color: '#ffffff',
    textAlign: 'center',
  },
  videoPlaceholder: {
    aspectRatio: 1,
    backgroundColor: '#f5f5f5',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#e0e0e0',
    borderStyle: 'dashed',
  },
  videoPlaceholderText: {
    fontSize: 14,
    fontFamily: "Yekan_Bakh_Regular",
    color: modernColors.medium,
    marginTop: 10,
    textAlign: 'center',
  },
  glassSection: {
    marginBottom: 20,
    backgroundColor: "rgba(248, 250, 252, 0.5)",
    borderRadius: 22,
    padding: 20,
    borderWidth: 1,
    borderColor: "rgba(203, 213, 225, 0.4)",
    position: "relative",
    overflow: "hidden",

    zIndex: 1,
    minHeight: 80,
  },
  sectionHeaderInfo: {
    flexDirection: "row-reverse",
    alignItems: "center",
    marginBottom: 15,
  },
  iconWrapper: {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 8,
  },
  sectionTitleInfo: {
    fontSize: 18,
    fontFamily: "Yekan_Bakh_Bold",
    color: modernColors.dark,
  },
  bioText: {
    fontSize: 16,
    fontFamily: "Yekan_Bakh_Regular",
    color: modernColors.dark,
    lineHeight: 28,
    textAlign: "left",
    letterSpacing: 0.3,
    wordSpacing: 2,
    marginBottom: 10,
    paddingVertical: 5,
    writingDirection: 'ltr',
    ...(Platform.OS === 'ios' && {
      writingDirection: 'rtl',
    }),
    ...(Platform.OS === 'android' && {
      includeFontPadding: false,
      textAlignVertical: 'center',
      writingDirection: 'rtl',
    }),
  },
  featureAccent: {
    position: "absolute",
    right: 0,
    top: 0,
    bottom: 0,
    width: 6,
    borderTopRightRadius: 22,
    borderBottomRightRadius: 22,
    shadowColor: "#000",
    shadowOffset: {
      width: 2,
      height: 0,
    },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  ellipsisText: {
    fontSize: 16,
    fontFamily: "Yekan_Bakh_Regular",
    color: modernColors.medium,
  },
  showMoreButton: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'flex-end',
    marginTop: 10,
    paddingVertical: 6,
    paddingHorizontal: 10,
    alignSelf: 'flex-end',
    backgroundColor: 'rgba(102, 126, 234, 0.1)',
    borderRadius: 12,
  },
  showMoreText: {
    fontSize: 14,
    fontFamily: "Yekan_Bakh_Bold",
    color: modernColors.primary,
    marginLeft: 4,
  },
  showLessButton: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'flex-end',
    marginTop: 10,
    paddingVertical: 6,
    paddingHorizontal: 10,
    alignSelf: 'flex-end',
    backgroundColor: 'rgba(102, 126, 234, 0.1)',
    borderRadius: 12,
  },
  showLessText: {
    fontSize: 14,
    fontFamily: "Yekan_Bakh_Bold",
    color: modernColors.primary,
    marginLeft: 4,
  },
  contactGrid: {
    gap: 12,
  },
  modernContactItem: {
    flexDirection: "row-reverse",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.8)",
    paddingHorizontal: 18,
    paddingVertical: 20,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.6)",
    position: 'relative',
    overflow: 'hidden',
    marginBottom: 8,
    minHeight: 70,
  },
  contactIconContainer: {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 15,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.8)",
  },
  contactTextContainer: {
    flex: 1,
    alignItems: 'flex-end',
  },
  contactLabel: {
    fontSize: 12,
    fontFamily: "Yekan_Bakh_Regular",
    color: modernColors.medium,
    marginBottom: 2,
  },
  modernContactText: {
    fontSize: 15,
    fontFamily: "Yekan_Bakh_Bold",
    color: modernColors.dark,
    textAlign: 'right',
  },
  contactArrow: {
    marginRight: 10,
    opacity: 0.6,
  },
  quickAccessContainer: {
    marginBottom: 30,
    marginTop: 15,
    paddingVertical: 15,
    zIndex: 1,
    position: 'relative',
  },
  quickAccessGrid: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 5,
  },
  quickAccessItem: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
    borderRadius: 18,
    flex: 1,
    marginHorizontal: 4,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.4)',
    maxWidth: (width - 60) / 4,
  },
  quickAccessText: {
    fontSize: 11,
    fontFamily: "Yekan_Bakh_Bold",
    color: modernColors.dark,
    marginTop: 6,
    textAlign: 'center',
  },
  sectionContainer: {
    marginBottom: 25,
  },
  sectionHeader: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 5,
    marginBottom: 20,
    marginTop: 10,
    minHeight: 40,
  },
  sectionTitleContainer: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
  },
  sectionTitle: {
    fontSize: 18,
    fontFamily: "Yekan_Bakh_Bold",
    color: modernColors.dark,
    marginRight: 8,
  },
  seeAllText: {
    fontSize: 14,
    fontFamily: "Yekan_Bakh_Regular",
    color: modernColors.primary,
  },
  horizontalList: {
    paddingHorizontal: 5,
  },
  portfolioCard: {
    width: 280,
    height: 200,
    borderRadius: 20,
    overflow: 'hidden',
    backgroundColor: modernColors.surface,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
    marginBottom: 20
  },
  portfolioImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  portfolioOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  portfolioGradient: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  portfolioContent: {
    padding: 15,
  },
  portfolioTitle: {
    fontSize: 16,
    fontFamily: "Yekan_Bakh_Bold",
    color: modernColors.surface,
    marginBottom: 5,
  },
  courseCard: {
    width: 300,
    backgroundColor: modernColors.surface,
    borderRadius: 20,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 2,
    marginBottom: 20
  },
  courseImage: {
    width: '100%',
    height: 140,
    resizeMode: 'cover',
  },
  courseContent: {
    padding: 15,
  },
  courseTitle: {
    fontSize: 16,
    fontFamily: "Yekan_Bakh_Bold",
    color: modernColors.dark,
    marginBottom: 10,
  },
  courseInfo: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  coursePrice: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
  },
  coursePriceText: {
    fontSize: 14,
    fontFamily: "Yekan_Bakh_Bold",
    color: modernColors.success,
    marginRight: 5,
  },
  productCard: {
    width: 180,
    backgroundColor: '#fff',
    borderRadius: 12,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 2,
    marginBottom: 20,
  },
  productImageContainer: {
    position: 'relative',
    width: '100%',
    aspectRatio: 1,
    backgroundColor: '#f5f5f5',
  },
  productImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  productContent: {
    padding: 12,
    minHeight: 85,
    justifyContent: 'space-between',
  },
  discountBadge: {
    position: 'absolute',
    top: 8,
    right: 8,
    backgroundColor: '#ff6b6b',
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 8,
  },
  discountText: {
    fontSize: 10,
    fontFamily: "Yekan_Bakh_Bold",
    color: '#fff',
  },
  unavailableBadge: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  unavailableText: {
    fontSize: 14,
    fontFamily: "Yekan_Bakh_Bold",
    color: '#fff',
  },
  productTitle: {
    fontSize: 13,
    fontFamily: "Yekan_Bakh_Bold",
    color: '#333',
    marginBottom: 4,
    textAlign: 'center',
    lineHeight: 16,
  },
  priceContainer: {
    alignItems: 'center',
    marginBottom: 4,
  },
  productPrice: {
    fontSize: 14,
    fontFamily: "Yekan_Bakh_Bold",
    color: '#667eea',
    textAlign: 'center',
  },
  originalPrice: {
    fontSize: 11,
    fontFamily: "Yekan_Bakh_Regular",
    color: '#999',
    textAlign: 'center',
    textDecorationLine: 'line-through',
  },
  specialPrice: {
    fontSize: 14,
    fontFamily: "Yekan_Bakh_Bold",
    color: '#ff6b6b',
    textAlign: 'center',
  },
  galleryCard: {
    width: 120,
    height: 120,
    borderRadius: 15,
    overflow: 'hidden',
    backgroundColor: modernColors.surface,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 2,
    position: 'relative',
    marginBottom: 20
  },
  galleryImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  galleryOverlay: {
    position: 'absolute',
    top: 8,
    right: 8,
  },
  galleryLikes: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  galleryLikesText: {
    fontSize: 11,
    fontFamily: "Yekan_Bakh_Bold",
    color: modernColors.surface,
    marginRight: 4,
  },
  blogCard: {
    width: 280,
    backgroundColor: '#ffffff',
    borderRadius: 20,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 1,
    elevation: 1,
    marginBottom: 20,
  },
  blogImageContainer: {
    height: 160,
    width: '100%',
    position: 'relative',
  },
  blogImage: {
    width: '100%',
    height: '100%',
  },
  blogImagePlaceholder: {
    flex: 1,
    backgroundColor: '#f5f5f5',
    justifyContent: 'center',
    alignItems: 'center',
    height: 160,
  },
  blogContent: {
    padding: 16,
  },
  blogTitle: {
    fontSize: 16,
    fontFamily: "Yekan_Bakh_Bold",
    color: "#2c3e50",
    textAlign: "right",
    lineHeight: 24,
    marginBottom: 12,
  },
  blogMeta: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  dateContainer: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
  },
  dateText: {
    fontSize: 12,
    fontFamily: "Yekan_Bakh_Regular",
    color: '#666',
    marginRight: 6,
  },
  likeContainer: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
  },
  likeText: {
    fontSize: 12,
    fontFamily: "Yekan_Bakh_Regular",
    color: '#666',
    marginRight: 8,
  },
  emptyStateContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
    paddingHorizontal: 20,
    width: width - 40,
  },
  emptyStateText: {
    fontSize: 14,
    fontFamily: "Yekan_Bakh_Regular",
    color: modernColors.medium,
    marginTop: 10,
    textAlign: 'center',
  },
  decorativeElements: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: -1,
  },
  star1: {
    position: "absolute",
    top: 300,
    left: 30,
  },
  star2: {
    position: "absolute",
    top: 600,
    right: 40,
  },
  star3: {
    position: "absolute",
    bottom: 200,
    left: 60,
  },
  bottomSpacer: {
    height: 50,
  },
  postImage: {
    height: "100%",
    width: "100%",
  },
});

